Mwozniak
NMarcin/MessengerOnFileForLinux pull request #28
Opened 2019-04-07 22:26 UTC by marcinwozniak0

2019-04-09 07:52 UTC, NMarcin commented
1. Zbyt długa pierwszy zdanie w commit msg -> jak popatrzysz wyżej to widać, że ucima.
2. Commit msg (pierwsze zdanie) nic, albo prawie nic nie mówi, szczególnie, że się powtarzają.

2019-04-09 18:00 UTC, marcinwozniak0 commented on MessengerOnFileForLinux/DisplayChat/src/InformationPrinter.hpp
>  class InformationPrinter
Ta nazwa mi się nie podoba za bardzo. Masz jakiś pomysł?

2019-04-10 08:00 UTC, mnurzyns requested changes

2019-04-10 08:00 UTC, mnurzyns commented on MessengerOnFileForLinux/DisplayChat/src/InformationPrinter.cpp
> +#include "InformationPrinter.hpp"
Refactor nazwy. Dopiero po wejściu do pliku wiem za co odpowiada, wcześniej miałem skojarzenie z jakimś loggerem.

2019-04-10 08:00 UTC, mnurzyns commented on MessengerOnFileForLinux/DisplayChat/src/UserServiceInformationPrinter.hpp
> +    void printInformation(const std::string&) const ;
jaką informację? Gdzie? Nazewnictwo prawie nic nam nie mówi. Po samej nazwie funkcji widzę, że najprawdopodobniej wydrukuje stringa, ale gdzie, jakiego i po co to już nie

2019-04-10 08:18 UTC, NMarcin commented on MessengerOnFileForLinux/DisplayChat/src/InformationPrinter.hpp
>  class InformationPrinter
widzę, że się zgadzamy XD

nie mam pomysłu na razie

2019-04-10 08:30 UTC, NMarcin commented on MessengerOnFileForLinux/DisplayChat/src/InformationPrinter.cpp
> +
te wszystkie 3 funkcje są idealnym przykładem duplikacji kodu, zachowaj gdzieś z nich diff to pokażemy na bakcylu

Refaktor:
- namespace z constexpr z wiadomościami
- jedna funkcja, która robi wszystko do "move(2,0)" włącznie, przekazujesz std::initializer_list 
- dedykowana funkcja dla każdego printa, gdzie wywołujesz tą wyżej i końcówkę
- ewentualnie można pokombinować z przekazywaniem też resztej części i miec jedną funkcję, ale nie widzę jak to zrobić czytelnie bez miliona parametrów i ifów

2019-04-10 08:32 UTC, NMarcin commented on MessengerOnFileForLinux/DisplayChat/src/InformationPrinter.hpp
> +    virtual void printInformation(const std::string&) const;
Jeżeli te virtuale są tylko do stubów to zrób klasę interfejs i klasę, która dziedziczy i to używa oraz zmień stuba tak by dziedziczył po interfejsi --> wydaje mi się, że jest jakiś pattern na to. Warto poszukać by zrobić to dobrze i ładnie, ja nie jestem pewny czy dobrze Ci powiedziałem.

2019-04-10 08:33 UTC, NMarcin commented on MessengerOnFileForLinux/TerminalFunctionality/test/CMakeLists.txt
> +    ${CMAKE_CURRENT_SOURCE_DIR}/TerminalFunctionalityTest.cpp
wyrównać dolary

2019-04-10 08:34 UTC, mnurzyns approved these changes

2019-04-10 12:25 UTC, merged